version: "3"

services:
  mining-pool-api:
    image: mining-pool-api:latest
    build: .
    restart: on-failure
    environment:
      DATABASE_URL: "postgres://admin:secret@postgresdb/mining_pool_api"
    ports:
      - "9090:9090"
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:12.2
    hostname: postgresdb
    restart: on-failure
    environment:
      POSTGRES_DB: mining_pool_api
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    volumes:
      - ./migrations/2022-04-25-102410_mining_pool_api/up.sql:/docker-entrypoint-initdb.d/up.sql
    ports:
      - "5432:5432"
