server:
  port: ${PORT:0}

spring:
  application:
    name: "users-service"
  devtools:
    restart:
      enabled: true
  datasource:
    url: "jdbc:h2:mem:testdb"
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8010/eureka"

