version: "3"

services:
  registry_service:
    image: registry_service:latest
    build:
      context: /discovery_service
      dockerfile: .
    restart: on-failure
    ports:
      - ""

  gateway_service:
    image: gateway_service:latest
    build:
      context: /gateway
      dockerfile: .
    restart: on-failure
    ports:
      - ""
    depends_on:
      - registry_service
      - mysqldb

  users_service:
    image: users_service
    build:
      context: /users_service
      dockerfile: .
    restart: on-failure
    ports:
      - ""
    depends_on:
      - registry_service
      - mysqldb

  account_management_service:
    image: account_management_service:latest
    build:
      context: /account_management_service
      dockerfile: .
    restart: on-failure
    ports:
      - ""
    depends_on:
      - registry_service
      - mysqldb

  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=test123
      - MYSQL_DATABASE=example
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
