version: "3"

services:
  app:
    container_name: farm_server
    image: farm_server:latest
    build:
      context: ""
      dockerfile: backend.Dockerfile
    restart: always
    ports:
      - "8080:8080"
    links:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo:3.6.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: